(* File auto-generated by obus-gen-interface, DO NOT EDIT. *)
open OBus_value
open OBus_value.C
open OBus_member
open OBus_object
module Com_redhat_oddjob_gpupdate =
struct
  let interface = "com.redhat.oddjob_gpupdate"
  let m_gpupdate = {
    Method.interface = interface;
    Method.member = "gpupdate";
    Method.i_args = (arg1
                       (Some "username", basic_string));
    Method.o_args = (arg0);
    Method.annotations = [];
  }
  let m_gpupdate_computer = {
    Method.interface = interface;
    Method.member = "gpupdate_computer";
    Method.i_args = (arg0);
    Method.o_args = (arg0);
    Method.annotations = [];
  }
  let m_gpupdatefor = {
    Method.interface = interface;
    Method.member = "gpupdatefor";
    Method.i_args = (arg1
                       (Some "username", basic_string));
    Method.o_args = (arg0);
    Method.annotations = [];
  }
  type 'a members = {
    m_gpupdate : 'a OBus_object.t -> string -> unit Lwt.t;
    m_gpupdate_computer : 'a OBus_object.t -> unit -> unit Lwt.t;
    m_gpupdatefor : 'a OBus_object.t -> string -> unit Lwt.t;
  }
  let make members =
    OBus_object.make_interface_unsafe interface
      [
      ]
      [|
        method_info m_gpupdate members.m_gpupdate;
        method_info m_gpupdate_computer members.m_gpupdate_computer;
        method_info m_gpupdatefor members.m_gpupdatefor;
      |]
      [|
      |]
      [|
      |]
end
