(* File auto-generated by obus-gen-interface, DO NOT EDIT. *)
open OBus_member
module Com_redhat_oddjob_gpupdate : sig
  val interface : OBus_name.interface
  val m_gpupdate : (string, unit) Method.t
  val m_gpupdate_computer : (unit, unit) Method.t
  val m_gpupdatefor : (string, unit) Method.t
  type 'a members = {
    m_gpupdate : 'a OBus_object.t -> string -> unit Lwt.t;
    m_gpupdate_computer : 'a OBus_object.t -> unit -> unit Lwt.t;
    m_gpupdatefor : 'a OBus_object.t -> string -> unit Lwt.t;
  }
  val make : 'a members -> 'a OBus_object.interface
end
